env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  indent: ['error', 'tab'],
  quotes: [2, 'single'],
  semi: [2, 'always'],
  no-tabs: 0,
  eqeqeq: 0,
  "require-jsdoc": "off",
}
