env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "indent":["error","tab"],
  "no-tabs": "off",
  "require-jsdoc": "off"
}
