name: 'Tweet when released'
on:
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Set secrets to env file
      run: |
        echo "TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }}" >> ./.env
        echo "TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }}" >> ./.env
        echo "TWITTER_ACCESS_TOKEN_KEY=${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}" >> ./.env
        echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> ./.env
    - name: Tweet
      run: |
        yarn tweet-test