on: 
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 */12 * * *'
  push: 
    paths:
      - '**.yml'

name: Update data
jobs:
  vaccination:
    name: Vaccinations
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Install Dependencies 🔧🟢
      run: yarn
    - name: ⬆️💉
      # env:
      #   USER_AGENT: ${{ secrets.USER_AGENT }}
      run: yarn vaccination 
    - name: tar to upload
      run: tar --exclude='./node_modules' -cvf vaccination.tar .
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-vaccination
        path: vaccination.tar
  case:
    name: Cases
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Install Dependencies 🔧🟢
      run: yarn
    - name: ⬆️🦠
      # env:
      #   USER_AGENT: ${{ secrets.USER_AGENT }}
      run: yarn case 
    - name: tar to upload
      run: tar --exclude='./node_modules' -cvf case.tar .
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-case
        path: case.tar

  vaccination-slack: 
    name: Send Vaccinations to Slack
    needs: [ vaccination ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: artifact-vaccination
        
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: path/to/artifact
    - name: Read Latest Daily
      id: VaccinationDaily
      uses: juliangruber/read-file-action@v1
      with:
        path: ./latest/vaccination/counter/today.json
    - name: Read Latest Today
      id: VaccinationToday
      uses: juliangruber/read-file-action@v1
      with:
        path: ./latest/vaccination/counter/today_c.json
    - name: Echo Latest Daily
      run: echo "${{ steps.vaccination-daily.outputs.content }}"
    - name: Echo Latest Today
      run: echo "${{ steps.vaccination-today.outputs.content }}"
    - name: Send Latest Daily message to Slack API
      uses: corcc/slack-send@v2.0.0
      id: notify-vaccination-daily
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN_VACCINATION }}
        slack-channel: ${{ secrets.SLACK_CHANNEL_VACCINATION_DAILY }}
        slack-text: "```${{ steps.vaccination-daily.outputs.content }}```"
    - name: Send Latest Today message to Slack API
      uses: corcc/slack-send@v2.0.0
      id: notify-vaccination-today
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN_VACCINATION }}
        slack-channel: ${{ secrets.SLACK_CHANNEL_VACCINATION_TODAY }}
        slack-text: "```${{ steps.vaccination-today.outputs.content }}```"
    - name: Result from "Send Message"
      run: echo "The result was ${{ steps.notify-vaccination-daily.outputs.slack-result }}"
    - name: Result from "Send Latest Today Message"
      run: echo "The result was ${{ steps.notify-vaccination-today.outputs.slack-result }}"
  case-slack: 
    name: Send Cases to Slack
    needs: [ case ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: artifact-case
        path: ./
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./
    - name: Read ./latest/case/counter.json
      id: case-today
      uses: juliangruber/read-file-action@v1
      with:
        path: ./latest/case/counter.json
    - name: Echo ./latest/case/counter.json
      run: echo "${{ steps.case-today.outputs.content }}"
    - name: Send Latest Today message to Slack API
      uses: corcc/slack-send@v2.0.0
      id: notify-case-today
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN_CONFIRMED_CASE }}
        slack-channel: ${{ secrets.SLACK_CHANNEL_CONFIRMED_CASE_TODAY }}
        slack-text: "```${{ steps.case-today.outputs.content }}```"
    - name: Result from "Send Message"
      run: echo "The result was ${{ steps.notify-case-today.outputs.slack-result }}"
  vaccination-publish:
    name: Upload Vaccinations
    needs: [ vaccination ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: artifact-vaccination
        path: ./
        
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./
    - uses: corcc/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        TASK_NAME: '⬆️💉'
        TIMEZONE: 'Asia/Tokyo'
  case-publish:
    name: Upload Cases 
    needs: [ case ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: artifact-case
        path: ./
        
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./
    - uses: corcc/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        TASK_NAME: '⬆️🦠'
        TIMEZONE: 'Asia/Tokyo'
