on: 
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 */1 * * *'
  push: 
    paths:
      - '**.yml'

name: Update data
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install

  vaccination:
    name: Vaccinations
    needs: [ install ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: ⬆️💉
      run: yarn vaccination 
    - name: tar to upload
      run: tar --exclude='./node_modules' --exclude='./.git' --exclude='*.tar.gz' -zcvf Vaccinations.tar.gz *
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-vaccination
        path: Vaccinations.tar.gz
  case:
    name: Cases
    needs: [ install ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./node_modules
    - name: ⬆️🦠
      run: yarn case 
    - name: tar to upload
      run: tar --exclude='./node_modules' --exclude='./.git' --exclude='*.tar.gz' -zcvf Cases.tar.gz *
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-case
        path: Cases.tar.gz

  vaccination-publish:
    name: Publish Vaccinations
    needs: [ install,vaccination ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: artifact-vaccination
        path: ./
    - name: Extract
      run: tar -zxvf Vaccinations.tar.gz
    - uses: corcc/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        TASK_NAME: '⬆️💉'
        TIMEZONE: 'Asia/Tokyo'
  case-publish:
    name: Publish Cases 
    needs: [ install,case ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: artifact-case
        path: ./
    - name: Extract
      run: tar -zxvf Cases.tar.gz
    - uses: corcc/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        TASK_NAME: '⬆️🦠'
        TIMEZONE: 'Asia/Tokyo'


  vaccination-plain-txt: 
    name: Make Vaccination Plain Text
    needs: [ install, vaccination,vaccination-publish ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Restore
      uses: actions/download-artifact@v2
      with:
        name: artifact-vaccination
        path: ./
    - name: Extract
      run: tar -zxvf Vaccinations.tar.gz
    - name: Make vaccination plain message
      run: yarn vaccination-plain-txt
    - run: tar --exclude='./node_modules' --exclude='./.git' --exclude='*.tar.gz' -zcvf Vaccinations_Plain_Text.tar.gz *
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-vaccination
        path: Vaccinations_Plain_Text.tar.gz
  case-plain-txt: 
    name: Make Case Plain Text
    needs: [ install, case,case-publish ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Restore
      uses: actions/download-artifact@v2
      with:
        name: artifact-case
        path: ./
    - name: Extract
      run: tar -zxvf Cases.tar.gz
    - name: Make vaccination plain message
      run: yarn case-plain-txt
    - run: tar --exclude='./node_modules' --exclude='./.git' --exclude='*.tar.gz' -zcvf Cases_Plain_Text.tar.gz *
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-case
        path: Cases_Plain_Text.tar.gz


  vaccination-daily-slack: 
    name: Send Daily Vaccinations to Slack
    needs: [ install, vaccination,vaccination-plain-txt ]
    # needs: [ install, vaccination ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: artifact-vaccination
        path: ./
    - name: Extract
      run: tar -zxvf Vaccinations_Plain_Text.tar.gz
      # run: tar -zxvf Vaccinations.tar.gz
    - name: Read Latest Daily
      id: vaccination-daily
      uses: juliangruber/read-file-action@v1
      with:
        path: ./plain/vaccination/counter/daily.slack.md
        # path: ./plain/vaccination/counter/daily.md
        # path: ./latest/vaccination/counter/daily.json
    - name: Echo Latest Daily
      run: echo "${{ steps.vaccination-daily.outputs.content }}"
    - name: Check Git Status
      run: echo $(git status | grep plain) >> ./git_status
    - name: Read Latest Today
      id: git-status
      uses: juliangruber/read-file-action@v1
      with:
        path: ./git_status
    - name: Echo Git Status 
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: echo "${{ steps.git-status.outputs.content }}"
    - name: Send to Slack API
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      uses: corcc/slack-send@v2.0.0
      id: notify-vaccination-daily
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN_VACCINATION }}
        slack-channel: ${{ secrets.SLACK_CHANNEL_VACCINATION_DAILY }}
        slack-text: "${{ steps.vaccination-daily.outputs.content }}"
    - name: Result from Slack API
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: echo "The result was ${{ steps.notify-vaccination-daily.outputs.slack-result }}"


  vaccination-today-tweet:
    name: Tweet Today's Vaccinations
    runs-on: ubuntu-latest
    needs: [ install, vaccination,vaccination-plain-txt ]
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Restore
      uses: actions/download-artifact@v2
      with:
        name: artifact-vaccination
        path: ./
    - name: Extract
      run: tar -zxvf Vaccinations_Plain_Text.tar.gz
      # run: tar -zxvf Vaccinations.tar.gz
    - name: Set secrets to env file
      run: |
        echo "TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }}" >> ./.env
        echo "TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }}" >> ./.env
        echo "TWITTER_ACCESS_TOKEN_KEY=${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}" >> ./.env
        echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> ./.env
    - name: Check Git Status
      run: echo $(git status | grep plain) >> ./git_status
    - name: Read Latest Today
      id: git-status
      uses: juliangruber/read-file-action@v1
      with:
        path: ./git_status
    - name: Echo Git Status 
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: echo "${{ steps.git-status.outputs.content }}"
    - name: Tweet Today's Vaccinations
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: yarn tweet-vaccination-today
    - name: Remove env file
      run: rm -rf ./.env

  case-today-tweet:
    name: Tweet Today's Cases
    runs-on: ubuntu-latest
    needs: [ install, case, case-plain-txt ]
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Restore
      uses: actions/download-artifact@v2
      with:
        name: artifact-case
        path: ./
    - name: Extract
      run: tar -zxvf Cases_Plain_Text.tar.gz
      # run: tar -zxvf Cases.tar.gz
    - name: Set secrets to env file
      run: |
        echo "TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }}" >> ./.env
        echo "TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }}" >> ./.env
        echo "TWITTER_ACCESS_TOKEN_KEY=${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}" >> ./.env
        echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> ./.env
    - name: Check Git Status
      run: echo $(git status | grep plain) >> ./git_status
    - name: Read Latest Today
      id: git-status
      uses: juliangruber/read-file-action@v1
      with:
        path: ./git_status
    - name: Echo Git Status 
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: echo "${{ steps.git-status.outputs.content }}"
    - name: Tweet Today's Cases
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: yarn tweet-case-today
    - name: Remove env file
      run: rm -rf ./.env


  vaccination-today-slack:
    name: Send Today's Vaccinations to Slack
    needs: [ install, vaccination,vaccination-plain-txt ]
    # needs: [ install, vaccination ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Restore
      uses: actions/download-artifact@v2
      with:
        name: artifact-vaccination
        path: ./
    - name: Extract
      run: tar -zxvf Vaccinations_Plain_Text.tar.gz
      # run: tar -zxvf Vaccinations.tar.gz
    - name: Read Latest Today
      id: vaccination-today
      uses: juliangruber/read-file-action@v1
      with:
        path: ./plain/vaccination/counter/today.slack.md
        # path: ./plain/vaccination/counter/today.md
        # path: ./latest/vaccination/counter/today.json
    - name: Echo Latest Today
      run: echo "${{ steps.vaccination-today.outputs.content }}"
    - name: Check Git Status
      run: echo $(git status | grep plain) >> ./git_status
    - name: Read Latest Today
      id: git-status
      uses: juliangruber/read-file-action@v1
      with:
        path: ./git_status
    - name: Echo Git Status 
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: echo "${{ steps.git-status.outputs.content }}"
    - name: Send to Slack API
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      uses: corcc/slack-send@v2.0.0
      id: notify-vaccination-today
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN_VACCINATION }}
        slack-channel: ${{ secrets.SLACK_CHANNEL_VACCINATION_TODAY }}
        slack-text: "${{ steps.vaccination-today.outputs.content }}"
    - name: Result from Slack API
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: echo "The result was ${{ steps.notify-vaccination-today.outputs.slack-result }}"

  case-slack: 
    name: Send Cases to Slack
    needs: [ install, case, case-plain-txt ]
    # needs: [ install, case ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - name: Restore
      uses: actions/download-artifact@v2
      with:
        name: artifact-case
        path: ./
    - name: Extract
      run: tar -zxvf Cases_Plain_Text.tar.gz
      # run: tar -zxvf Cases.tar.gz
    - name: Read Today's Confirmed Case
      id: case-today
      uses: juliangruber/read-file-action@v1
      with:
        path: ./plain/case/counter.slack.md
        # path: ./plain/case/counter.md
        # path: ./latest/case/counter.json
    - name: Echo Today's Confirmed Case
      run: echo "${{ steps.case-today.outputs.content }}"
    - name: Check Git Status
      run: echo $(git status | grep plain) >> ./git_status
    - name: Read Latest Today
      id: git-status
      uses: juliangruber/read-file-action@v1
      with:
        path: ./git_status
    - name: Echo Git Status 
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: echo "${{ steps.git-status.outputs.content }}"
    - name: Send to Slack API
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      uses: corcc/slack-send@v2.0.0
      id: notify-case-today
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN_CONFIRMED_CASE }}
        slack-channel: ${{ secrets.SLACK_CHANNEL_CONFIRMED_CASE_TODAY }}
        slack-text: "${{ steps.case-today.outputs.content }}"
    - name: Result from Slack API
      if: "${{ !(steps.git-status.outputs.content != '' && steps.git-status.outputs.content == '\n') }}"
      run: echo "The result was ${{ steps.notify-case-today.outputs.slack-result }}"



  vaccination-plain-txt-publish:
    name: Publish Vaccinations Plain Text
    needs: [ install, vaccination, vaccination-plain-txt ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: artifact-vaccination
        path: ./
    - name: Extract
      run: tar -zxvf Vaccinations_Plain_Text.tar.gz
    - uses: corcc/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        TASK_NAME: '⬆️💉📄'
        TIMEZONE: 'Asia/Tokyo'

  case-plain-txt-publish:
    name: Publish Cases Plain Text
    needs: [ install, case, case-plain-txt ]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout 🛎️
      uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: artifact-case
        path: ./
    - name: Extract
      run: tar -zxvf Cases_Plain_Text.tar.gz
    - uses: corcc/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        TASK_NAME: '⬆️🦠📄'
        TIMEZONE: 'Asia/Tokyo'